### ISSUE TITLE
depulicaton warning を消す

### ISSUE THREAD

**Issue by waterlow** [waterlow/rebuild-search#62]
テストのときに出るやつ
```
DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false= is deprecated and will be removed in Rails 5.2. (called from <top (required)> at /Users/waterlow/src/github.com/waterlow/rebuild-search/config/initializers/callback_terminator.rb:6)
```

**Comment by waterlow** [comment]
```
(node:53266) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (/Users/waterlow/src/github.com/waterlow/rebuild-search/node_modules/loader-utils/index.js:78:3)
    at Object.module.exports (/Users/waterlow/src/github.com/waterlow/rebuild-search/node_modules/babel-loader/lib/index.js:104:35)
    at LOADER_EXECUTION (/Users/waterlow/src/github.com/waterlow/rebuild-search/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/waterlow/src/github.com/waterlow/rebuild-search/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/waterlow/src/github.com/waterlow/rebuild-search/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/waterlow/src/github.com/waterlow/rebuild-search/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/waterlow/src/github.com/waterlow/rebuild-search/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at /Users/waterlow/src/github.com/waterlow/rebuild-search/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
    at /Users/waterlow/src/github.com/waterlow/rebuild-search/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
```
